[project]
name = "qr-ui"
version = "0.1.0"
description = "A GUI for generating QR codes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "amzqr>=0.0.1",
    "loguru>=0.7.3",
    "streamlit>=1.46.1",
]
